/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iracalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author Ethan
 */
public class IRAJPanelForm extends javax.swing.JPanel {

    public static String textInYearlyContributionsTF;

    /**
     * Creates new form IRAJPanelForm
     */
    public IRAJPanelForm() {
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        retirementAgejComboBox1.setSelectedIndex(64);
        currentAgejComboBox1.setSelectedIndex(21);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yearlyContributionsTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        balanceTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        roiTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inflationTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        retirementAgejComboBox1 = new javax.swing.JComboBox<>();
        currentAgejComboBox1 = new javax.swing.JComboBox<>();
        moreJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        contributionAmountTF3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contributionAmountTF2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        contributionAmountTF1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        beginAgejComboBox1 = new javax.swing.JComboBox<>();
        beginAgejComboBox2 = new javax.swing.JComboBox<>();
        endAgejComboBox1 = new javax.swing.JComboBox<>();
        endAgejComboBox2 = new javax.swing.JComboBox<>();
        beginAgejComboBox3 = new javax.swing.JComboBox<>();
        endAgejComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        yearlyContributionsTF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        yearlyContributionsTF.setText("5200");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Current balance ($):");

        balanceTF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        balanceTF.setText("22000");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Inflation rate (%):");

        roiTF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        roiTF.setText("10.1");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Yearly contributions ($):");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Retirement age:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Rate of return (%):");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Current age:");

        inflationTF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        inflationTF.setText("2.75");
        inflationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inflationTFActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        retirementAgejComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        retirementAgejComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        currentAgejComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        currentAgejComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        moreJButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moreJButton.setText("More");
        moreJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(moreJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inflationTF)
                            .addComponent(roiTF)
                            .addComponent(yearlyContributionsTF)
                            .addComponent(balanceTF)
                            .addComponent(retirementAgejComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentAgejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(yearlyContributionsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(inflationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(currentAgejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(retirementAgejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moreJButton)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("IRA Summary by Year...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(180, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("I will contribute $");

        contributionAmountTF3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        contributionAmountTF3.setText("3500");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("per year when I am between");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("per year when I am between");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("years old and");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("per year when I am between");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("years old and");

        contributionAmountTF2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        contributionAmountTF2.setText("3000");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("I will contribute $");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("years old.");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setText("I will contribute $");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("years old.");

        contributionAmountTF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        contributionAmountTF1.setText("5500");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("years old and");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("years old.");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Below, you can specify how much you'll contribute based on how old you are.");

        beginAgejComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        beginAgejComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not used", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        beginAgejComboBox2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        beginAgejComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not used", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        endAgejComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        endAgejComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not used", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        endAgejComboBox2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        endAgejComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not used", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        beginAgejComboBox3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        beginAgejComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not used", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        endAgejComboBox3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        endAgejComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not used", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("How does this work?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contributionAmountTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beginAgejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contributionAmountTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beginAgejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(169, 169, 169))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endAgejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endAgejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endAgejComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(contributionAmountTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(beginAgejComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contributionAmountTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(beginAgejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(endAgejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contributionAmountTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(beginAgejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(endAgejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contributionAmountTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(beginAgejComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(endAgejComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inflationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inflationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inflationTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Before doing anything else, make sure the user entered valid data.
            inputIsValid();

            double realROI = Double.parseDouble(roiTF.getText());  // realROI - the IRA's interest rate minus inflation rate.
            realROI -= Double.parseDouble(inflationTF.getText());
            realROI /= 100.0;

            double balance = Double.parseDouble(balanceTF.getText());  // balance - the amount of money in the IRA
            int age = Integer.parseInt("" + currentAgejComboBox1.getSelectedItem());        // age - the current age of the user in years
            int retirementAge = Integer.parseInt("" + retirementAgejComboBox1.getSelectedItem()); // retirementAge - age at which the user plans on retiring

            int yearsToContribute = Integer.parseInt(contributionAmountTF1.getText());  // yearsToContribute - the number of years the user will contribute to the IRA
            double yearlyContributions = 0;
            if (!jPanel3.isVisible()) {
                yearlyContributions = Double.parseDouble(yearlyContributionsTF.getText());
            }
            double totalContributions = 0.0;

            jPanel2.setVisible(true);  // Unhide the panel that shows an overview of IRA.
            jTextArea1.setText("");
            if (yearlyContributions > 0 || (beginAgejComboBox1.getSelectedIndex() != 0 && endAgejComboBox1.getSelectedIndex() != 0) || (beginAgejComboBox2.getSelectedIndex() != 0 && endAgejComboBox2.getSelectedIndex() != 0) || (beginAgejComboBox3.getSelectedIndex() != 0 && endAgejComboBox3.getSelectedIndex() != 0)) {  // If user is going to contribute something, then let them know that their contributions don't include the beginning balance.
                jTextArea1.append(" (Contributions shown below do not include beginning balance.)\n");
            }
            jTextArea1.append(" Initial balance: $" + (int) balance + "\n");

            int beginAge1 = -2;
            int endAge1 = -1;
            int beginAge2 = -2;
            int endAge2 = -1;
            int beginAge3 = -2;
            int endAge3 = -1;
            double contribute1 = 0;
            double contribute2 = 0;
            double contribute3 = 0;
            if (beginAgejComboBox1.getSelectedIndex() != 0 && endAgejComboBox1.getSelectedIndex() != 0) {
                beginAge1 = Integer.parseInt("" + beginAgejComboBox1.getSelectedItem());
                endAge1 = Integer.parseInt("" + endAgejComboBox1.getSelectedItem());
                contribute1 = Double.parseDouble("" + contributionAmountTF1.getText());
            }
            if (beginAgejComboBox2.getSelectedIndex() != 0 && endAgejComboBox2.getSelectedIndex() != 0) {
                beginAge2 = Integer.parseInt("" + beginAgejComboBox2.getSelectedItem());
                endAge2 = Integer.parseInt("" + endAgejComboBox2.getSelectedItem());
                contribute2 = Double.parseDouble("" + contributionAmountTF2.getText());
            }
            if (beginAgejComboBox3.getSelectedIndex() != 0 && endAgejComboBox3.getSelectedIndex() != 0) {
                beginAge3 = Integer.parseInt("" + beginAgejComboBox3.getSelectedItem());
                endAge3 = Integer.parseInt("" + endAgejComboBox3.getSelectedItem());
                contribute3 = Double.parseDouble("" + contributionAmountTF3.getText());
            }
            while (age != retirementAge) {
                if (jPanel3.isVisible()) {
                    // If the current age is between one of those specified by data entered in More details, then use that contribution amount.
                    if (age >= beginAge1 && age < endAge1) {
                        yearlyContributions = contribute1;
                    } else if (age >= beginAge2 && age < endAge2) {
                        yearlyContributions = contribute2;
                    } else if (age >= beginAge3 && age < endAge3) {
                        yearlyContributions = contribute3;
                    } else {
                        yearlyContributions = 0;
                    }
                }

                balance *= (1.0 + realROI);
                if (yearsToContribute > 0) {
                    totalContributions += yearlyContributions;
                    balance += yearlyContributions;
                    yearsToContribute--;
                }
                age++;
                String balanceWithCommas = createStringWithCommas((int) balance);
                String contributionsWithCommas = createStringWithCommas((int) (totalContributions));
                if (age < retirementAge) {
                    jTextArea1.append(" IRA worth at age " + age + ": $" + balanceWithCommas);
                    jTextArea1.append(". Contributions: $" + contributionsWithCommas + "\n");
                } else {  // Reached retirement age.
                    jTextArea1.append("---------------------------------------------------------------------------------------");
                    jTextArea1.append("\n IRA worth at age " + age + " (adjusted to inflation): $" + balanceWithCommas + ".\n Total contributions: $" + contributionsWithCommas);
                }
            }
            jTextArea1.append("\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputIsValid() throws Exception {
        if (yearlyContributionsTF.isEnabled()) {  // will be using this text field for the amount contributed per year
            // make sure yearly contributions is valid
            try {
                double amount = Double.parseDouble(yearlyContributionsTF.getText());
            } catch (NumberFormatException nfe) {
                throw new Exception("Invalid input for yearly contributions: " + yearlyContributionsTF.getText()
                        + "\nMust be a numeric value.");
            }
        } else // Other contribution text fields are visible. Check their inputs.
        {
            if (beginAgejComboBox1.getSelectedIndex() != 0 && endAgejComboBox1.getSelectedIndex() != 0) {
                try {
                    double amount = Double.parseDouble(contributionAmountTF1.getText());
                } catch (NumberFormatException nfe) {
                    throw new Exception("Invalid input for first span of yearly contributions: " + contributionAmountTF1.getText()
                            + "\nMust be a numeric value.");
                }
            }
            if (beginAgejComboBox2.getSelectedIndex() != 0 && endAgejComboBox2.getSelectedIndex() != 0) {
                try {
                    double amount = Double.parseDouble(contributionAmountTF2.getText());
                } catch (NumberFormatException nfe) {
                    throw new Exception("Invalid input for second span of yearly contributions: " + contributionAmountTF2.getText()
                            + "\nMust be a numeric value.");
                }
            }
            if (beginAgejComboBox3.getSelectedIndex() != 0 && endAgejComboBox3.getSelectedIndex() != 0) {
                try {
                    double amount = Double.parseDouble(contributionAmountTF3.getText());
                } catch (NumberFormatException nfe) {
                    throw new Exception("Invalid input for third span of yearly contributions: " + contributionAmountTF3.getText()
                            + "\nMust be a numeric value.");
                }
            }
        }

        // make sure beginning balance is valid
        try {
            double beginBal = Double.parseDouble(balanceTF.getText());
        } catch (NumberFormatException nfe) {
            throw new Exception("Invalid input for current balance: " + balanceTF.getText()
                    + "\nMust be a numeric value.");
        }
        // check ROI
        try {
            double roi = Double.parseDouble(roiTF.getText());
        } catch (NumberFormatException nfe) {
            throw new Exception("Invalid input for ROI: " + roiTF.getText()
                    + "\nMust be a numeric value.");
        }
        // check inflation rate
        try {
            double inflation = Double.parseDouble(inflationTF.getText());
        } catch (NumberFormatException nfe) {
            throw new Exception("Invalid input for inflation rate: " + inflationTF.getText()
                    + "\nMust be a numeric value.");
        }

        int retirementAge = Integer.parseInt("" + retirementAgejComboBox1.getSelectedItem());
        int currentAge = Integer.parseInt("" + currentAgejComboBox1.getSelectedItem());

        int beginAge1 = -2;
        int endAge1 = -1;
        int beginAge2 = -2;
        int endAge2 = -1;
        int beginAge3 = -2;
        int endAge3 = -1;
        if (beginAgejComboBox1.getSelectedIndex() != 0 && endAgejComboBox1.getSelectedIndex() != 0) {
            beginAge1 = Integer.parseInt("" + beginAgejComboBox1.getSelectedItem());
            endAge1 = Integer.parseInt("" + endAgejComboBox1.getSelectedItem());
        }
        if (beginAgejComboBox2.getSelectedIndex() != 0 && endAgejComboBox2.getSelectedIndex() != 0) {
            beginAge2 = Integer.parseInt("" + beginAgejComboBox2.getSelectedItem());
            endAge2 = Integer.parseInt("" + endAgejComboBox2.getSelectedItem());
        }
        if (beginAgejComboBox3.getSelectedIndex() != 0 && endAgejComboBox3.getSelectedIndex() != 0) {
            beginAge3 = Integer.parseInt("" + beginAgejComboBox3.getSelectedItem());
            endAge3 = Integer.parseInt("" + endAgejComboBox3.getSelectedItem());
        }

        // Check that all begin ages are less than end ages.
        if (beginAge1 >= endAge1 || beginAge2 >= endAge2 || beginAge3 >= endAge3) {
            throw new Exception("Check custom contributions ages! Begin ages must all be less than end ages.");
        }

        // Check that all begin ages are greater than or equal to the current age.
        if ((beginAge1 < currentAge && beginAge1 > 0) || (beginAge2 < currentAge && beginAge2 > 0) || (beginAge3 < currentAge && beginAge3 > 0)) {
            throw new Exception("All begin ages must be greater than or equal to current ages.");
        }

        // Check that end ages are all less than the retirement age.
        if (endAge1 > retirementAge || endAge2 > retirementAge || endAge3 > retirementAge) {
            throw new Exception("Retirement age must be greater than all end ages.");
        }

        if (currentAge >= retirementAge) {
            throw new Exception("Current age must be less than retirement age.");
        }

        // Make sure there is no overlap in the age spans.
        if ((beginAge1 > 0 && ((beginAge1 >= beginAge2 && beginAge1 < endAge2) || (beginAge1 >= beginAge3 && beginAge1 < endAge3))) || (beginAge2 > 0 && ((beginAge2 >= beginAge1 && beginAge2 < endAge1) || (beginAge2 >= beginAge3 && beginAge2 < endAge3))) || (beginAge3 > 0 && ((beginAge3 >= beginAge2 && beginAge3 < endAge2) || (beginAge3 >= beginAge1 && beginAge3 < endAge1)))) {
            throw new Exception("Can't have overlap between the different age spans. If you wish to not use a span, simply leave one of the drop-downs as \"Not used\" for that span.");
        }
    }

    private void moreJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreJButtonActionPerformed
        if (moreJButton.getText().equals("More")) {
            moreJButton.setText("Less");

            textInYearlyContributionsTF = yearlyContributionsTF.getText();  // Save the text that the user may have entered. Will display it later if user clicks "Less".

            // Select reasonable ages.
            beginAgejComboBox1.setSelectedIndex(0);
            beginAgejComboBox2.setSelectedIndex(0);
            beginAgejComboBox3.setSelectedIndex(0);
            endAgejComboBox1.setSelectedIndex(0);
            endAgejComboBox2.setSelectedIndex(0);
            endAgejComboBox3.setSelectedIndex(0);

            jPanel3.setVisible(true);
            showRegularContributions(false);  // Hide the normal contributions text field and label.
        } else {
            yearlyContributionsTF.setText(textInYearlyContributionsTF);  // Restore text in text field.
            moreJButton.setText("More");
            jPanel3.setVisible(false);
            showRegularContributions(true);
        }
    }//GEN-LAST:event_moreJButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String message = "In the three fields below, enter your begin and end age "
                + "\nfor different contribution timespans. For example, you can "
                + "\nspecify that you contribute $2,500 per year when you are 25-33 "
                + "\nyears old, $3,000 when you are 33-37 years old, and that you "
                + "\ndon't contribute anything when you are over 37 (just leave one "
                + "\nof the drop-downs in the last group as \"Not Used\").";
        JOptionPane.showMessageDialog(null, message);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showRegularContributions(boolean value) {
        if (!value) {
            yearlyContributionsTF.setText("N/A");
        }
        yearlyContributionsTF.setEnabled(value);
        jLabel2.setEnabled(value);
    }

    public static String createStringWithCommas(int n) {
        String strWithCommas = "" + (int) n;
        int index = strWithCommas.length();
        int threeCount = 0;
        while (index >= 1) {
            if (threeCount % 3 == 0 && threeCount != 0) {
                strWithCommas = strWithCommas.substring(0, index) + "," + strWithCommas.substring(index);
            }
            index--;
            threeCount++;
        }
        return strWithCommas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceTF;
    private javax.swing.JComboBox<String> beginAgejComboBox1;
    private javax.swing.JComboBox<String> beginAgejComboBox2;
    private javax.swing.JComboBox<String> beginAgejComboBox3;
    private javax.swing.JTextField contributionAmountTF1;
    private javax.swing.JTextField contributionAmountTF2;
    private javax.swing.JTextField contributionAmountTF3;
    private javax.swing.JComboBox<String> currentAgejComboBox1;
    private javax.swing.JComboBox<String> endAgejComboBox1;
    private javax.swing.JComboBox<String> endAgejComboBox2;
    private javax.swing.JComboBox<String> endAgejComboBox3;
    private javax.swing.JTextField inflationTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton moreJButton;
    private javax.swing.JComboBox<String> retirementAgejComboBox1;
    private javax.swing.JTextField roiTF;
    private javax.swing.JTextField yearlyContributionsTF;
    // End of variables declaration//GEN-END:variables
}
