/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iracalculator;

/**
 *
 * @author Ethan
 */
public class IRAJPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form IRAJPanelForm
     */
    public IRAJPanelForm() {
        initComponents();
        resultsLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        yearlyContributionsTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        balanceTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        roiTF = new javax.swing.JTextField();
        retirementAgeTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yearsToContributeTF = new javax.swing.JTextField();
        currentAgeTF = new javax.swing.JTextField();
        inflationTF = new javax.swing.JTextField();

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resultsLabel.setText("jLabel8");

        yearlyContributionsTF.setText("500");

        jLabel1.setText("Current balance:");

        balanceTF.setText("20000");

        jLabel4.setText("Inflation %:");

        roiTF.setText("10.1");

        retirementAgeTF.setText("65");

        jLabel7.setText("Years you contribute till retirement:");

        jLabel2.setText("Yearly contributions:");

        jLabel6.setText("Retirement age:");

        jLabel3.setText("Rate of return:");

        jLabel5.setText("Current age:");

        yearsToContributeTF.setText("28");

        currentAgeTF.setText("22");

        inflationTF.setText("2.75");
        inflationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inflationTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yearsToContributeTF)
                    .addComponent(retirementAgeTF)
                    .addComponent(currentAgeTF)
                    .addComponent(inflationTF)
                    .addComponent(roiTF)
                    .addComponent(yearlyContributionsTF)
                    .addComponent(balanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlyContributionsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retirementAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearsToContributeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jButton1)))
                        .addGap(0, 352, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(resultsLabel)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inflationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inflationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inflationTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double realROI = Double.parseDouble(roiTF.getText());
        realROI -= Double.parseDouble(inflationTF.getText());
        realROI /= 100.0;

        double balance = Double.parseDouble(balanceTF.getText());
        double beginningBalance = balance;
        int age = Integer.parseInt(currentAgeTF.getText());
        int retirementAge = Integer.parseInt(retirementAgeTF.getText());

        int yearsToContribute = Integer.parseInt(yearsToContributeTF.getText());
        double yearlyContributions = Double.parseDouble(yearlyContributionsTF.getText());
        double totalContributions = 0.0;

        System.out.println("beg. age: " + age);
        System.out.println("roi: " + realROI);
        System.out.println("retirement age: " + retirementAge);
        System.out.println();
        boolean interestAlert = false;
        while (age != retirementAge) {
            balance *= (1.0 + realROI);
            if (yearsToContribute > 0) {
                totalContributions += yearlyContributions;
                balance += yearlyContributions;
                yearsToContribute--;
            }
            age++;
            if (!interestAlert && ((int) totalContributions + beginningBalance) < ((int) balance - beginningBalance)) {
                System.out.println("Interest finally beats contributions!!!");
                System.out.println("Retirement account worth at age " + age + ": $" + ((int) balance));
                System.out.println("Contributions: $" + ((int) totalContributions + beginningBalance) + " (this includes the beginning balance!!!)\n");
                interestAlert = true;
            } else {
                System.out.println("Retirement account worth at age " + age + ": $" + ((int) balance));
                System.out.println("Contributions: $" + ((int) totalContributions + beginningBalance) + " (this includes the beginning balance!!!)\n");
            }
        }
        resultsLabel.setVisible(true);
        String balanceWithCommas = createStringWithCommas((int) balance);
        String contributionsWithCommas = createStringWithCommas((int) totalContributions);

        resultsLabel.setText("Retirement account worth at age " + age + ": $" + balanceWithCommas + ". Total contributions: $" + contributionsWithCommas + " (not including beginning balance!)");
        System.out.println("------------------------------------------------------------------------------------------\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    public static String createStringWithCommas(int n) {
        String strWithCommas = "" + (int) n;
        int index = strWithCommas.length();
        int threeCount = 0;
        while (index >= 1) {
            if (threeCount % 3 == 0 && threeCount != 0) {
                strWithCommas = strWithCommas.substring(0, index) + "," + strWithCommas.substring(index);
            }
            index--;
            threeCount++;
        }
        return strWithCommas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceTF;
    private javax.swing.JTextField currentAgeTF;
    private javax.swing.JTextField inflationTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JTextField retirementAgeTF;
    private javax.swing.JTextField roiTF;
    private javax.swing.JTextField yearlyContributionsTF;
    private javax.swing.JTextField yearsToContributeTF;
    // End of variables declaration//GEN-END:variables
}
